version: '3.8'

services:
  postgres:
    image: postgres:latest   # Use the official PostgreSQL image
    container_name: my-postgres
    ports:
      - "5444:5432"           # Map port 5444 on host to 5432 inside the container
    environment:
      POSTGRES_USER: root   # Set the PostgreSQL username
      POSTGRES_PASSWORD: root  # Set the PostgreSQL password
      POSTGRES_DB: user-management-db

  sonarqube:
    image: sonarqube:lts-community
    depends_on:
      - postgres
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/user-management-db
      SONAR_JDBC_USERNAME: root
      SONAR_JDBC_PASSWORD: root
    ports:
      - "9001:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp


volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
