name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3


      # Step 3: Build the project (create the /target directory)
      - name: Install dependencies and build
        run: mvn clean install

      # Step 4: Debug step to confirm the target directory exists (optional)
      - name: Verify target directory
        run: ls -la target

      # Step 5: Run SonarQube analysis
      - name: SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN2 }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn -B verify \
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=user-management-ci \
          -Dsonar.projectName='user-management-ci' \
          -Dsonar.java.binaries=target






